version: "3"

services:
  db:
    image: postgres
    ports:
      - 5434:5432
    expose:
      - 5432
    environment:
      POSTGRES_DB: euroleague
      POSTGRES_USER: euroleague
      POSTGRES_PASSWORD: euroleague
      PG_USER: euroleague

    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d euroleague -U euroleague"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    restart: on-failure:5
    networks:
      - euroleague
  
  identity:
    container_name: identity
    image: quay.io/keycloak/keycloak:23.0.6
    ports:
      - '8081:8080'
      - '8443:8443'
    environment:
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_SCHEMA: identity
      KC_DB_URL: jdbc:postgresql://db:5432/identity
      KC_DB_USERNAME: euroleague
      KC_DB_PASSWORD: euroleague
      KC_PROXY_ADDRESS_FORWARDING: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY_HEADERS: forwarded
      KC_PROXY: edge
    command: start
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - db
    networks:
      - euroleague

volumes:
  db_data:

networks:
  euroleague:
