version: "3"

services:
  db:
    image: postgres
    ports:
      - 5434:5432
    expose:
      - 5432
    environment:
      POSTGRES_DB: euroleague
      POSTGRES_USER: euroleague
      POSTGRES_PASSWORD: euroleague
      PG_USER: euroleague

    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d euroleague -U euroleague"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    restart: on-failure:5

volumes:
  db_data:
